build:library:
  image: node:8
  before_script:
  - npm ci
  script:
  - npm run build-library
  - mkdir markdown-to-pdf
  - copy dist/main.js markdown-to-pdf/converter.min.js
  - sed -e 's/main\.js/converter.min.js/' < dist/index.html >markdown-to-pdf/demo.html
  - copy LICENSE markdown-to-pdf/
  - copy README.md markdown-to-pdf/
  artifacts:
    name: "markdown-to-pdf-$CI_COMMIT_REF_NAME"
    paths:
    - markdown-to-pdf/
